# Generated by Django 3.1.1 on 2020-09-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EmailService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_tls', models.BooleanField(default=False)),
                ('host', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('port', models.CharField(max_length=255)),
                ('from_email', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.CharField(max_length=255)),
                ('emails', models.ManyToManyField(to='email_service.Email')),
            ],
        ),
    ]
